### ISSUE TITLE
Add Postman collection for all API methods.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/developer-docs#362]
As discussed in the call and Discord, this repo seems the best place for such a collection.

**Comment by shamardy** [comment]
After some research, this schema is the one I found most fitting for documenting mm2 APIs in postman, please suggest improvements if you have any:

An example request for electrum for UTXO coins can look like this:
```
{
    "userpass": "{{userpass}}",
    "method": "electrum",
    "coin": "RICK",
    "servers": [
        {
            "url": "electrum1.cipig.net:10017"
            // "protocol": "TCP" // Accepted values: "TCP", "SSL", "WS", "WSS"
            // "disable_cert_verification": false
        },
        {
            "url": "electrum2.cipig.net:10017"
        },
        {
            "url": "electrum3.cipig.net:10017"
        }
    ]
    // "mm2": null, // Accepted values: 0, 1
    // "tx_history": false,
    // "required_confirmations": null, // Accepted values: Integers
    // "requires_notarization": false,
    // "utxo_merge_params": null
    // // "utxo_merge_params": {
    // //     "merge_at":50
    // //     // "check_every":10,
    // //     // "max_merge_at_once":100
    // //     }
}
```

- All non-commented params are required params. I will provide example values for those params.
- Any commented-out parameters are optional parameters, this provides easy usage of these parameters since anyone who would like to use them will have to comment them in. 
- Optional parameters provided values will be the default values, for enums and null values I will add an accepted values comment as shown.
- Optional parameters can also have multiple levels like `utxo_merge_params` so the same schema will be used for nested params.
- For multilevel optional parameters there will be 2 comments, one with the default value if there is any as `"utxo_merge_params": null` and another showing the structure inside it using the same schema.
-  If at any point we would like to add a playground webpage similar to the ones auto-generated by swagger and similar tools, the above schema can be easily parsed from the postman collection .json file, of course, it will take some effort to develop such webpage.

**Comment by smk762** [comment]
closing as completed
