### ISSUE TITLE
Code-examples

### ISSUE THREAD

**Issue by gerritoerlemans** [KomodoPlatform/developer-docs#451]
This concerns all the curl-example commands, which are quite complicated to read and build. That is mainly because you use a double quote embracing the content of the --data parameter.  If you make it a single quote you can remove all the back-slashes within.

eg 	           curl --silent --url 'http://127.0.0.1:7783' --data '{"coin":"EFL","method":"my_balance","userpass":"xxx"}'
instead of    curl --silent --url 'http://127.0.0.1:7783' --data "{\\"coin\\":\\"EFL\\",\\"method\\":\\"my_balance\\",\\"userpass\\":\\"xxx\\"}"

**Comment by gcharang** [comment]
hey, thanks for the suggestion. we are aware of this and the reason we are using escaped double quotes right now is to maintain compatibility for Windows users. we have a docs overhaul coming soon and this issue is fixed there as we have tabs for different programming langs and various OS terminals in each code block
