### ISSUE TITLE
Better landing page

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/developer-docs#67]
Re: Removal of landing page in the `dev-theme` branch
My suggestion is to keep the landing page and add various CTA to it, like: `Getstarted` as it existed previously, `create assetchain`, `explore cc modules`
I remember before we removed the extra text in the previous landing page, there was a readymade format for that. 

Now, even though we have removed the need for one click, but still the other starting points are many clicks away, even if users know where to navigate. 

But if all these CTA are in the previous landing page, then the users can choose where they want to go

**Comment by siddhartha-crypto** [comment]
I would prefer that we make sure the sidebar is available on whatever page the user chooses.

When a regular user of Komodo comes to the initial page, they will already know where they want to go according to the sidebar. We don't want them to have to remember where to click on a landing page, and then also where to click on the sidebar. 

We can, however, make more CTA buttons on the Introduction page, so that those people who are actually reading the landing page for their first time can find an easier pathway in.
